version: '3.8'
services:
  docs-generator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    