version: '3.8'
services:
  docs-generator:
    image: node:20-alpine
    container_name: docs-generator-dev
    working_dir: /app
    environment:
      - PORT=5555
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    command: npm run dev 